export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header style={{background: "lightBlue", fontSize: "20px", padding: "20px"}}>Header</header>
        <main>{children}</main>
        <footer style={{background: "lightGreen", fontSize: "20px", padding: "20px"}}>Footer</footer>
      </body>
    </html>
  );
}
