import Nav from "@/components/Nav";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "Next.js Tutorial - Codevalution",
    template: "%s | Codevolution",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header
          style={{ background: "lightBlue", fontSize: "20px", padding: "20px" }}
        >
          <Nav/>
        </header>
        <main>{children}</main>
        <footer
          style={{
            background: "lightGreen",
            fontSize: "20px",
            padding: "20px",
          }}
        >
          Footer
        </footer>
      </body>
    </html>
  );
}
